//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCart
    {
        public int CreditCartID { get; set; }
        public string CartOwner { get; set; }
        public string CardNumber { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> Limit { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
