//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProductInformationEntities : DbContext
    {
        public ProductInformationEntities()
            : base("name=ProductInformationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brands> Brands1 { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CreditCart> CreditCarts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Models> Models1 { get; set; }
        public virtual DbSet<MyCart> MyCarts { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductTypes> ProductTypes1 { get; set; }
        public virtual DbSet<Shipper> Shippers { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<SP_ProdStockByType_Result> SP_ProdStockByType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ProdStockByType_Result>("SP_ProdStockByType");
        }
    
        public virtual ObjectResult<SP_ModelByBrand_Result> SP_ModelByBrand()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ModelByBrand_Result>("SP_ModelByBrand");
        }
    }
}
