//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyCart
    {
        public int MyCartID { get; set; }
        public string MyCart1 { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
