//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.MyCarts = new HashSet<MyCart>();
            this.Orders = new HashSet<Order>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string OutputYear { get; set; }
        public string Color { get; set; }
        public Nullable<int> Stock { get; set; }
        public string WarrantyPeriod { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public string Photo3 { get; set; }
    
        public virtual Brands Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Models Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyCart> MyCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ProductTypes ProductType { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
